// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEYgADBGqDFNNsXFlcUzvfkHPlRU3RMdY',
    appId: '1:464935510828:web:bd1a7aa9b1ac8f512d0289',
    messagingSenderId: '464935510828',
    projectId: 'amor-app-parejas',
    authDomain: 'amor-app-parejas.firebaseapp.com',
    storageBucket: 'amor-app-parejas.firebasestorage.app',
    measurementId: 'G-RRB3LM09TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLn1OIJEn-7j5SH_STjJeKQqtXGUuMvWI',
    appId: '1:464935510828:android:1d164c602fe7f3d42d0289',
    messagingSenderId: '464935510828',
    projectId: 'amor-app-parejas',
    storageBucket: 'amor-app-parejas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFU3slOO7xMQBikKEAXVmZo2Gc1_RV4w',
    appId: '1:464935510828:ios:4d627bee1b0d58642d0289',
    messagingSenderId: '464935510828',
    projectId: 'amor-app-parejas',
    storageBucket: 'amor-app-parejas.firebasestorage.app',
    iosBundleId: 'com.example.amorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFU3slOO7xMQBikKEAXVmZo2Gc1_RV4w',
    appId: '1:464935510828:ios:4d627bee1b0d58642d0289',
    messagingSenderId: '464935510828',
    projectId: 'amor-app-parejas',
    storageBucket: 'amor-app-parejas.firebasestorage.app',
    iosBundleId: 'com.example.amorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEYgADBGqDFNNsXFlcUzvfkHPlRU3RMdY',
    appId: '1:464935510828:web:5469786690a82c602d0289',
    messagingSenderId: '464935510828',
    projectId: 'amor-app-parejas',
    authDomain: 'amor-app-parejas.firebaseapp.com',
    storageBucket: 'amor-app-parejas.firebasestorage.app',
    measurementId: 'G-89JB4VBCM4',
  );
}
